apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    io.rancher.sidekicks: gitea-conf
    kompose.cmd: /home/oleg/Downloads/migration-tools_linux-amd64 parse
    kompose.version: 1.16.0 (HEAD)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"io.rancher.sidekicks":"gitea-conf","kompose.cmd":"/home/oleg/Downloads/migration-tools_linux-amd64 parse","kompose.version":"1.16.0 (HEAD)"},"creationTimestamp":null,"labels":{"io.kompose.service":"gitea"},"name":"gitea","namespace":"gitea"},"spec":{"replicas":0,"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"io.kompose.service":"gitea"}},"spec":{"containers":[{"env":[{"name":"GITEA_CUSTOM","value":"/app/gitea/custom"}],"image":"gitea/gitea:1.6.0-rc1","name":"gitea","resources":{},"volumeMounts":[{"mountPath":"/data","name":"gitea-data"}]}],"restartPolicy":"Always","volumes":[{"name":"gitea-data","persistentVolumeClaim":{"claimName":"gitea-data"}}]}}},"status":{}}
  creationTimestamp: "2019-12-07T08:17:59Z"
  generation: 2
  labels:
    io.kompose.service: gitea
  name: gitea
  namespace: gitea
  resourceVersion: "2607973"
  selfLink: /apis/apps/v1/namespaces/gitea/deployments/gitea
  uid: 3daf7a14-88e8-4638-875c-c9ee469c2d1c
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gitea
    spec:
      containers:
      - env:
        - name: GITEA_CUSTOM
          value: /app/gitea/custom
        image: gitea/gitea:1.6.0-rc1
        imagePullPolicy: IfNotPresent
        name: gitea
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: gitea-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-07T08:18:53Z"
    lastUpdateTime: "2019-12-07T08:18:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
